name: fit_office
description: A stay fit in the office app.
publish_to: 'none'
version: 1.0.1


environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  google_fonts: ^6.1.0
  intl: ^0.20.2

  ## -- STATE MANAGEMENT
  get: ^4.6.6
  get_storage: ^2.1.1

  ## -- OnBoarding PACKAGES
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.1.0

  ## -- OTP TEXT FIELD PACKAGE
  flutter_otp_text_field: ^1.1.1

  ## -- FIREBASE PACKAGES
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5

  ## -- ICON PACKAGES
  cupertino_icons: ^1.0.6
  line_awesome_flutter: ^3.0.1
  flutter_native_splash: ^2.4.0
  string_similarity: ^2.1.1
  supabase_flutter: ^2.8.4
  image_picker: ^1.1.2

  ## -- New Packages
  crop_your_image: ^2.0.0
  cached_network_image: ^3.4.0
  video_player: ^2.9.5
  chewie: ^1.10.0
  auto_size_text: ^3.0.0
  lottie: ^3.3.1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  tutorial_coach_mark: ^1.3.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

## -- Overrides
dependency_overrides:
  async: ^2.13.0
  vector_math: ^2.1.5
  fake_async: ^1.3.3
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.2
  lints: ^6.0.0
  material_color_utilities: ^0.12.0
  vm_service: ^15.0.0

flutter:
  uses-material-design: true
  generate: true # TODO: WILL BE DEPRECATED IN FUTURE (CHANGE TO FLUTTER GEN)
  assets:
    - assets/logo/
    - assets/images/
    - assets/images/profile/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/
    - assets/lottie/

# Splash screen has been added in the 'splash.yaml' file in main project directory
