import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps
/// These options are generated by the FlutterFire CLI and should not be modified manually.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbQN6o0e-uBXpTdytOsvNyl6Pq960OhA8',
    appId: '1:271322425039:android:ae3152268dae7dd5eaf9ba',
    messagingSenderId: '271322425039',
    projectId: 'fitoffice-dhbw',
    databaseURL: 'https://fitoffice-dhbw-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitoffice-dhbw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwsrlvsfUnGN8wDCdGeKtLmyoczCG38JM',
    appId: '1:271322425039:ios:84ff4f16ab75fda2eaf9ba',
    messagingSenderId: '271322425039',
    projectId: 'fitoffice-dhbw',
    databaseURL: 'https://fitoffice-dhbw-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitoffice-dhbw.firebasestorage.app',
    iosClientId: '271322425039-ndi620epvjg3qo331jo7b4eo0jvhmeue.apps.googleusercontent.com',
    iosBundleId: 'de.dhbw-ravensburg.FitOffice',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB26KhKRa1h8yxK4JrXj44hlNBTSoZAj3Q',
    appId: '1:271322425039:web:0bb36b35282c351eeaf9ba',
    messagingSenderId: '271322425039',
    projectId: 'fitoffice-dhbw',
    authDomain: 'fitoffice-dhbw.firebaseapp.com',
    databaseURL: 'https://fitoffice-dhbw-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitoffice-dhbw.firebasestorage.app',
    measurementId: 'G-YT0QH6K479',
  );

}